# This file controls which parts of the wallet_object_template.json are generated
# based on the action ('initial', 'update').
# If a key is not listed here, it is considered 'initial' by default.
# The format is key=action or parent.key=action.

[generation_rules]
id = initial
classId = initial
version = initial
state = initial
heroImage = initial
barcode = initial
header = initial
wideLogo = initial
imageModulesData = initial
textModulesData = initial
linksModuleData = update
appLinkData = update
valueAddedModuleData = disabled